spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
