spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

